<?php
//Custom Layouts
$layouts = array(
		'custom_818' => array(
				'name' => 'Banners',
				'template' => '[vc_row equal_height=\"yes\"][vc_column width=\"1/2\"][vc_empty_space alter_height=\"large\" hide_on_mobile=\"\" css=\".vc_custom_1486978514417{margin-bottom: 1.1rem !important;}\"][trx_sc_action type=\"default\" full_height=\"\" actions=\"%5B%7B%22position%22%3A%22mc%22%2C%22title%22%3A%22free%20delivery%22%2C%22description%22%3A%22on%20all%20orders%20%3Cspan%3Eover%20%2450%3C%2Fspan%3E%22%2C%22link%22%3A%22%2Fshop%2F%22%2C%22link_text%22%3A%22order%20now!%22%2C%22bg_image%22%3A%22269%22%2C%22icon_type%22%3A%22fontawesome%22%7D%5D\" slider=\"\" title_style=\"default\"][/vc_column][vc_column width=\"1/2\"][vc_empty_space alter_height=\"large\" hide_on_mobile=\"\" css=\".vc_custom_1486978514417{margin-bottom: 1.1rem !important;}\"][trx_sc_action type=\"default\" full_height=\"\" actions=\"%5B%7B%22position%22%3A%22mc%22%2C%22title%22%3A%22All%20your%20favorite%20food%22%2C%22description%22%3A%22%3Cspan%3Ein%20one%20place%3C%2Fspan%3E%22%2C%22bg_image%22%3A%22270%22%2C%22icon_type%22%3A%22fontawesome%22%7D%5D\" slider=\"\" title_style=\"default\"][/vc_column][/vc_row][vc_row][vc_column][vc_empty_space alter_height=\"huge\" hide_on_mobile=\"\" css=\".vc_custom_1486981048301{margin-bottom: 0.6rem !important;}\"][trx_sc_icons align=\"center\" size=\"medium\" icons_animation=\"\" icons=\"%5B%7B%22title%22%3A%22Choose%20your%20location%22%2C%22icon_type%22%3A%22fontawesome%22%2C%22icon_fontawesome%22%3A%22icon-icon1%22%7D%2C%7B%22title%22%3A%22Choose%20restaurant%22%2C%22icon_type%22%3A%22fontawesome%22%2C%22icon_fontawesome%22%3A%22icon-icon2%22%7D%2C%7B%22title%22%3A%22Make%20your%20order%22%2C%22icon_type%22%3A%22fontawesome%22%2C%22icon_fontawesome%22%3A%22icon-icon3%22%7D%2C%7B%22title%22%3A%22Food%20is%20on%20the%20way%22%2C%22icon_type%22%3A%22fontawesome%22%2C%22icon_fontawesome%22%3A%22icon-icon4%22%7D%5D\" title_style=\"default\" title_align=\"center\" columns=\"4\" title=\"Get your food fast &amp; easy\" subtitle=\"Follow the Steps\" link=\"\" link_text=\"\" link_image=\"\"][vc_empty_space alter_height=\"huge\" hide_on_mobile=\"\" css=\".vc_custom_1486983839318{margin-bottom: -1.2rem !important;}\"][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'custom'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1486978514417{margin-bottom: 1.1rem !important;}.vc_custom_1486978514417{margin-bottom: 1.1rem !important;}.vc_custom_1486981048301{margin-bottom: 0.6rem !important;}.vc_custom_1486983839318{margin-bottom: -1.2rem !important;}'
						)
				),
		'footer_9' => array(
				'name' => 'Footer Fullwidth simple',
				'template' => '[vc_row row_type=\"narrow\" row_delimiter=\"\" row_fixed=\"\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" css=\".vc_custom_1486466968728{background-image: url(http://fooddy.dv.ancorathemes.com/wp-content/uploads/2016/12/main_bg.jpg?id=505) !important;}\"][vc_column column_align=\"center\" icons_position=\"left\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\"][vc_empty_space height=\"\" alter_height=\"huge\" hide_on_mobile=\"\"][vc_row_inner][vc_column_inner width=\"1/3\" icons_position=\"left\" offset=\"vc_col-lg-5 vc_col-md-5\"][vc_column_text]
<p style=\"text-align: right;\">Chicago, IL
60606 123, New Lenox

[/vc_column_text][vc_empty_space height=\"\" alter_height=\"small\" hide_on_mobile=\"\"][/vc_column_inner][vc_column_inner width=\"1/3\" icons_position=\"left\" offset=\"vc_col-lg-2 vc_col-md-2\"][vc_single_image image=\"452\" img_size=\"142x54\" alignment=\"center\"][vc_empty_space height=\"\" alter_height=\"small\" hide_on_mobile=\"\"][/vc_column_inner][vc_column_inner width=\"1/3\" column_align=\"left\" icons_position=\"left\" offset=\"vc_col-lg-5 vc_col-md-5\"][vc_column_text css=\".vc_custom_1486467280743{margin-bottom: -0.1rem !important;}\"]
<p style=\"text-align: left;\">Call us 24/7</p>

[/vc_column_text][trx_sc_layouts_iconed_text icon_type=\"fontawesome\" icon_fontawesome=\"fa fa-phone\" text2=\"094 711 80 58\"][vc_empty_space height=\"\" alter_height=\"small\" hide_on_mobile=\"\"][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner width=\"1/3\" icons_position=\"left\" offset=\"vc_hidden-sm vc_hidden-xs\"][/vc_column_inner][vc_column_inner icons_position=\"left\" offset=\"vc_col-lg-4 vc_col-md-4\"][trx_widget_socials align=\"center\"][/vc_column_inner][vc_column_inner width=\"1/3\" icons_position=\"left\" offset=\"vc_hidden-sm vc_hidden-xs\"][/vc_column_inner][/vc_row_inner][/trx_sc_content][/vc_column][/vc_row][vc_row row_type=\"narrow\" row_delimiter=\"\" row_fixed=\"\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" css=\".vc_custom_1486470009579{background-image: url(http://fooddy.dv.ancorathemes.com/wp-content/uploads/2016/12/main_bg.jpg?id=505) !important;}\"][vc_column column_align=\"center\" icons_position=\"left\"][vc_empty_space height=\"3.9rem\" alter_height=\"none\" hide_on_mobile=\"\"][vc_wp_text]<a href=\"https://themeforest.net/user/ancorathemes/portfolio\"> Ancora Themes </a> &copy; 2017. All Rights Reserved <a href=\"http://ancorathemes.com/about/\">Terms of Use</a> and <a href=\"http://ancorathemes.com/about/\">Privacy Policy</a>[/vc_wp_text][vc_empty_space height=\"2rem\" alter_height=\"small\" hide_on_mobile=\"\" css=\".vc_custom_1487255099849{margin-bottom: 0.4rem !important;}\"][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'footer'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1486466968728{background-image: url(http://fooddy.dv.ancorathemes.com/wp-content/uploads/2016/12/main_bg.jpg?id=505) !important;}.vc_custom_1486470009579{background-image: url(http://fooddy.dv.ancorathemes.com/wp-content/uploads/2016/12/main_bg.jpg?id=505) !important;}.vc_custom_1486467280743{margin-bottom: -0.1rem !important;}.vc_custom_1487255099849{margin-bottom: 0.4rem !important;}'
						)
				),
		'footer_11' => array(
				'name' => 'Footer Standard',
				'template' => '[vc_row row_type=\"normal\" row_delimiter=\"1\" row_fixed=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" css=\".vc_custom_1487252950207{padding-bottom: 0px !important;background-image: url(http://fooddy.dv.ancorathemes.com/wp-content/uploads/2016/12/main_bg.jpg?id=505) !important;}\"][vc_column icons_position=\"left\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\"][vc_row_inner][vc_column_inner width=\"1/2\" icons_position=\"left\" offset=\"vc_col-lg-3 vc_col-md-3\"][trx_widget_contacts columns=\"\" googlemap=\"\" socials=\"\" logo=\"848\"][/trx_widget_contacts][/vc_column_inner][vc_column_inner width=\"1/2\" icons_position=\"left\" offset=\"vc_col-lg-3 vc_col-md-3\"][vc_wp_custommenu title=\"Site Links\" nav_menu=\"41\"][/vc_column_inner][vc_column_inner width=\"1/2\" icons_position=\"left\" offset=\"vc_col-lg-3 vc_col-md-3\"][trx_widget_recent_posts number=\"2\" show_image=\"\" show_counters=\"\" show_categories=\"\" title=\"From the Blog\"][/vc_column_inner][vc_column_inner width=\"1/2\" icons_position=\"left\" offset=\"vc_col-lg-3 vc_col-md-3\"][trx_widget_contacts columns=\"\" googlemap=\"\" socials=\"1\" description=\"Chicago, IL 60606 123, New Lenox
Call us 24/7\" phone=\"094 711 80 58\"][/trx_widget_contacts][/vc_column_inner][/vc_row_inner][/trx_sc_content][/vc_column][/vc_row][vc_row row_type=\"narrow\" row_delimiter=\"\" row_fixed=\"\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" css=\".vc_custom_1487253047109{padding-top: 3.2rem !important;padding-bottom: 2.4rem !important;}\"][vc_column icons_position=\"left\"][trx_sc_content size=\"1_1\" float=\"center\" number_position=\"br\" title_style=\"default\"][vc_wp_text]<a href=\"http://themeforest.net/user/ancorathemes/portfolio\" target=\"_blank\">Ancora &copy; 2017</a> All rights reserved. <a href=\"#\" target=\"_blank\">Terms of use</a> and <a href=\"#\" target=\"_blank\">Privacy Policy</a>[/vc_wp_text][/trx_sc_content][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'footer'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1487252950207{padding-bottom: 0px !important;background-image: url(http://fooddy.dv.ancorathemes.com/wp-content/uploads/2016/12/main_bg.jpg?id=505) !important;}.vc_custom_1487253047109{padding-top: 3.2rem !important;padding-bottom: 2.4rem !important;}'
						)
				),
		'custom_798' => array(
				'name' => 'Get Our Weekly Email',
				'template' => '[vc_row full_width=\"stretch_row\" css=\".vc_custom_1484232850616{background-color: #ffbd2f !important;}\"][vc_column][vc_empty_space alter_height=\"medium\" hide_on_mobile=\"\" css=\".vc_custom_1486997360019{margin-bottom: -0.3rem !important;}\"][trx_sc_title title_style=\"default\" title_tag=\"h4\" title_align=\"center\" scheme=\"dark\" title=\"Want Coupons or Deep Thoughts About Food? Get Our Weekly Email:\"][vc_empty_space hide_on_mobile=\"\" css=\".vc_custom_1486997423485{margin-bottom: 0.35rem !important;}\"][vc_column_text scheme=\"dark\"][mc4wp_form id=\"660\"][/vc_column_text][vc_empty_space alter_height=\"large\" hide_on_mobile=\"\" css=\".vc_custom_1486997989612{margin-top: -0.65rem !important;}\"][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'custom'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1484232850616{background-color: #ffbd2f !important;}.vc_custom_1486997360019{margin-bottom: -0.3rem !important;}.vc_custom_1486997423485{margin-bottom: 0.35rem !important;}.vc_custom_1486997989612{margin-top: -0.65rem !important;}'
						)
				),
		'header_17' => array(
				'name' => 'Header Centered menu',
				'template' => '[vc_row row_type=\"compact\" row_delimiter=\"\" row_fixed=\"\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\"][vc_column icons_position=\"left\" column_type=\"center\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\" width=\"1_1\" width2=\"1_1\"][vc_row_inner equal_height=\"yes\" content_placement=\"middle\"][vc_column_inner width=\"1/3\" column_align=\"left\" icons_position=\"left\" offset=\"vc_col-lg-4 vc_col-md-4\"][trx_sc_layouts_iconed_text icon_type=\"fontawesome\" hide_on_tablet=\"1\" hide_on_mobile=\"1\" text1=\"Call us for Ordering\"][trx_sc_layouts_iconed_text icon_type=\"fontawesome\" icon_fontawesome=\"fa fa-phone\" text2=\"094 711 80 58\"][/vc_column_inner][vc_column_inner width=\"1/3\" column_align=\"center\" icons_position=\"left\" offset=\"vc_col-lg-4 vc_col-md-4\"][vc_empty_space hide_on_mobile=\"\" css=\".vc_custom_1487254203370{margin-top: -0.4rem !important;}\"][trx_sc_layouts_logo][vc_empty_space hide_on_mobile=\"\" css=\".vc_custom_1487254287610{margin-bottom: -0.6rem !important;}\"][/vc_column_inner][vc_column_inner width=\"1/3\" column_align=\"right\" icons_position=\"left\" offset=\"vc_col-lg-4 vc_col-md-4\"][trx_sc_layouts_login hide_on_mobile=\"1\"][trx_sc_layouts_cart text=\"Shopping Cart\" hide_on_mobile=\"1\"][/vc_column_inner][/vc_row_inner][/trx_sc_content][/vc_column][/vc_row][vc_row row_type=\"compact\" row_delimiter=\"\" row_fixed=\"1\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" css=\".vc_custom_1487254778419{padding-top: 0.1rem !important;padding-bottom: 0.1rem !important;background-image: url(http://fooddy.dv.ancorathemes.com/wp-content/uploads/2016/12/main_bg.jpg?id=505) !important;}\"][vc_column column_align=\"center\" icons_position=\"left\" column_type=\"center\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\" width=\"1_1\" width2=\"1_1\"][vc_row_inner equal_height=\"yes\" content_placement=\"middle\"][vc_column_inner column_align=\"center\" icons_position=\"left\"][trx_sc_layouts_menu location=\"none\" menu=\"main-menu\" animation_in=\"fadeInUpSmall\" animation_out=\"fadeOutDownSmall\" mobile_button=\"1\" mobile_menu=\"1\" hide_on_mobile=\"1\" burger=\"\" mobile=\"1\" stretch=\"\" mobile_hide=\"1\"][/vc_column_inner][/vc_row_inner][/trx_sc_content][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'header'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1487254778419{padding-top: 0.1rem !important;padding-bottom: 0.1rem !important;background-image: url(http://fooddy.dv.ancorathemes.com/wp-content/uploads/2016/12/main_bg.jpg?id=505) !important;}.vc_custom_1487254203370{margin-top: -0.4rem !important;}.vc_custom_1487254287610{margin-bottom: -0.6rem !important;}'
						)
				),
		'header_21' => array(
				'name' => 'Header Short',
				'template' => '[vc_row row_type=\"narrow\" row_delimiter=\"\" row_fixed=\"\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" css=\".vc_custom_1486461101895{background-image: url(http://fooddy.dv.ancorathemes.com/wp-content/uploads/2016/12/main_bg.jpg?id=505) !important;}\"][vc_column column_align=\"center\" icons_position=\"left\" column_type=\"center\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\" width=\"1_1\" width2=\"1_1\"][vc_row_inner equal_height=\"yes\" content_placement=\"middle\"][vc_column_inner width=\"1/2\" column_align=\"left\" icons_position=\"left\"][trx_sc_layouts_iconed_text icon_type=\"fontawesome\" text1=\"Call us for Ordering\"][trx_sc_layouts_iconed_text icon_type=\"fontawesome\" icon_fontawesome=\"fa fa-phone\" text2=\"094 711 80 58\"][/vc_column_inner][vc_column_inner width=\"1/2\" column_align=\"right\" icons_position=\"left\"][trx_sc_layouts_login hide_on_mobile=\"1\"][/vc_column_inner][/vc_row_inner][/trx_sc_content][/vc_column][/vc_row][vc_row row_type=\"compact\" row_delimiter=\"1\" row_fixed=\"1\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" css=\".vc_custom_1487256896480{background-color: #ffffff !important;}\"][vc_column icons_position=\"left\" column_type=\"center\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\" width=\"1_1\" width2=\"1_1\"][vc_row_inner equal_height=\"yes\" content_placement=\"middle\"][vc_column_inner width=\"1/6\" column_align=\"left\" icons_position=\"left\"][trx_sc_layouts_logo][/vc_column_inner][vc_column_inner width=\"5/6\" column_align=\"right\" icons_position=\"left\"][trx_sc_layouts_menu location=\"none\" menu=\"main-menu\" hover=\"roll_down\" animation_in=\"fadeInUpSmall\" animation_out=\"fadeOutDownSmall\" mobile_button=\"1\" mobile_menu=\"1\" hide_on_mobile=\"1\" burger=\"\" mobile=\"1\" stretch=\"\" mobile_hide=\"1\"][trx_sc_layouts_cart text=\"Cart:\" hide_on_tablet=\"1\" hide_on_mobile=\"1\" css=\".vc_custom_1487262977435{margin-right: 1rem !important;}\"][vc_empty_space height=\"0.55rem\" alter_height=\"none\" hide_on_mobile=\"\"][/vc_column_inner][/vc_row_inner][/trx_sc_content][/vc_column][/vc_row][vc_row scheme=\"dark\" row_type=\"normal\" row_delimiter=\"\" row_fixed=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"1\" css=\".vc_custom_1486464309994{background: #f7f7f7 url(http://fooddy.dv.ancorathemes.com/wp-content/uploads/2016/12/home2_slide1.jpg?id=506) !important;}\"][vc_column column_align=\"center\" icons_position=\"left\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\"][trx_sc_layouts_title meta=\"\" title=\"1\" breadcrumbs=\"1\" icon_type=\"fontawesome\" icon_fontawesome=\"\"][/trx_sc_content][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'header'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1486461101895{background-image: url(http://fooddy.dv.ancorathemes.com/wp-content/uploads/2016/12/main_bg.jpg?id=505) !important;}.vc_custom_1487256896480{background-color: #ffffff !important;}.vc_custom_1486464309994{background: #f7f7f7 url(http://fooddy.dv.ancorathemes.com/wp-content/uploads/2016/12/home2_slide1.jpg?id=506) !important;}'
						)
				),
		'header_810' => array(
				'name' => 'Header Short (dark)',
				'template' => '[vc_row scheme=\"dark\" row_type=\"narrow\" row_delimiter=\"\" row_fixed=\"\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" css=\".vc_custom_1487168118200{background-color: #222020 !important;}\"][vc_column column_align=\"center\" icons_position=\"left\" column_type=\"center\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\" width=\"1_1\" width2=\"1_1\"][vc_row_inner equal_height=\"yes\" content_placement=\"middle\"][vc_column_inner width=\"1/2\" column_align=\"left\" icons_position=\"left\"][trx_sc_layouts_iconed_text icon_type=\"fontawesome\" text1=\"Call us for Ordering\"][trx_sc_layouts_iconed_text icon_type=\"fontawesome\" icon_fontawesome=\"fa fa-phone\" text2=\"094 711 80 58\"][/vc_column_inner][vc_column_inner width=\"1/2\" column_align=\"right\" icons_position=\"left\"][trx_sc_layouts_login hide_on_mobile=\"1\"][/vc_column_inner][/vc_row_inner][/trx_sc_content][/vc_column][/vc_row][vc_row row_type=\"compact\" row_delimiter=\"\" row_fixed=\"1\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\"][vc_column icons_position=\"left\" column_type=\"center\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\" width=\"1_1\" width2=\"1_1\"][vc_row_inner equal_height=\"yes\" content_placement=\"middle\"][vc_column_inner width=\"1/6\" column_align=\"left\" icons_position=\"left\"][trx_sc_layouts_logo logo=\"817\"][/vc_column_inner][vc_column_inner width=\"5/6\" column_align=\"right\" icons_position=\"left\"][trx_sc_layouts_menu location=\"none\" menu=\"main-menu\" hover=\"roll_down\" animation_in=\"fadeInUpSmall\" animation_out=\"fadeOutDownSmall\" mobile_button=\"1\" mobile_menu=\"1\" hide_on_mobile=\"1\" burger=\"\" mobile=\"1\" stretch=\"\" mobile_hide=\"1\"][trx_sc_layouts_cart text=\"Cart:\" hide_on_tablet=\"1\" hide_on_mobile=\"1\" css=\".vc_custom_1487263585642{margin-right: 1rem !important;}\"][vc_empty_space height=\"0.55rem\" alter_height=\"none\" hide_on_mobile=\"\"][/vc_column_inner][/vc_row_inner][/trx_sc_content][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'header'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1487168118200{background-color: #222020 !important;}'
						)
				),
		'custom_710' => array(
				'name' => 'Search in form',
				'template' => '[vc_row][vc_column icons_position=\"left\"][trx_sc_layouts_search style=\"address\" ajax=\"\"][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'custom'
								)
						)
				),
		'custom_674' => array(
				'name' => 'Why People Choose Us',
				'template' => '[vc_row full_width=\"stretch_row\" css=\".vc_custom_1484234816688{background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}\"][vc_column icons_position=\"left\"][vc_empty_space alter_height=\"superhuge\" hide_on_mobile=\"\"][trx_sc_title title_style=\"default\" title_align=\"center\" title=\"Why People Choose Us\" subtitle=\"Clients’ Most Popular Choise\"][vc_empty_space alter_height=\"medium\" hide_on_mobile=\"\" css=\".vc_custom_1486999992930{margin-bottom: 0.3rem !important;}\"][/vc_column][vc_column width=\"1/2\" icons_position=\"left\" offset=\"vc_col-lg-3 vc_col-md-3\"][trx_sc_services type=\"default\" featured=\"number\" featured_position=\"right\" hide_excerpt=\"\" no_margin=\"\" icons_animation=\"\" orderby=\"none\" slider=\"\" title_style=\"default\" count=\"3\" columns=\"1\" css=\".vc_custom_1487000028072{margin-top: 0.25rem !important;}\"][vc_empty_space alter_height=\"medium\" hide_on_mobile=\"\" css=\".vc_custom_1487000851137{margin-bottom: -1.05rem !important;}\"][/vc_column][vc_column width=\"1/2\" icons_position=\"left\" offset=\"vc_hidden-sm vc_hidden-xs\"][vc_single_image image=\"680\" img_size=\"full\" alignment=\"right\" css=\".vc_custom_1487002943299{margin-top: -1rem !important;}\"][/vc_column][vc_column width=\"1/2\" icons_position=\"left\" offset=\"vc_col-lg-3 vc_col-md-3\"][trx_sc_services type=\"default\" featured=\"number\" featured_position=\"left\" hide_excerpt=\"\" no_margin=\"\" icons_animation=\"\" orderby=\"none\" slider=\"\" title_style=\"default\" offset=\"3\" count=\"3\" columns=\"1\" css=\".vc_custom_1487000032616{margin-top: 0.25rem !important;}\"][vc_empty_space alter_height=\"medium\" hide_on_mobile=\"\" css=\".vc_custom_1487000851137{margin-bottom: -1.05rem !important;}\"][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'custom'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1484234816688{background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}.vc_custom_1486999992930{margin-bottom: 0.3rem !important;}.vc_custom_1487000028072{margin-top: 0.25rem !important;}.vc_custom_1487000851137{margin-bottom: -1.05rem !important;}.vc_custom_1487002943299{margin-top: -1rem !important;}.vc_custom_1487000032616{margin-top: 0.25rem !important;}.vc_custom_1487000851137{margin-bottom: -1.05rem !important;}'
						)
				),
		'custom_821' => array(
				'name' => 'Your First Order',
				'template' => '[vc_row full_width=\"stretch_row\" css=\".vc_custom_1486977813880{background-color: #ffbd2f !important;}\"][vc_column width=\"7/12\"][vc_empty_space alter_height=\"small\" hide_on_mobile=\"\" css=\".vc_custom_1486983938205{margin-top: 0.5rem !important;}\"][trx_sc_title title_style=\"default\" title_tag=\"h5\" title_align=\"right\" scheme=\"dark\" title=\"Get $40 on Your First Order\"][/vc_column][vc_column width=\"5/12\"][vc_empty_space alter_height=\"small\" hide_on_mobile=\"\" css=\".vc_custom_1486983956359{margin-top: -2px !important;}\"][trx_sc_button type=\"inverse\" align=\"left\" icon_type=\"fontawesome\" icon_position=\"left\" link=\"#\" title=\"Details\"][vc_empty_space hide_on_mobile=\"\" css=\".vc_custom_1486983981680{margin-bottom: 0.1rem !important;}\"][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'custom'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1486977813880{background-color: #ffbd2f !important;}.vc_custom_1486983938205{margin-top: 0.5rem !important;}.vc_custom_1486983956359{margin-top: -2px !important;}.vc_custom_1486983981680{margin-bottom: 0.1rem !important;}'
						)
				)
		);
?>